### ISSUE TITLE
Transformer Layer

### ISSUE THREAD

**Issue by pedrommone** [ezdeliveryco/snorlax#1]
Would be helpful if we can have a transformer layer, so every item of collection can be parsed into a "usable" object.

**transfomers/post.php**
```php
public function transform(Resource $resource)
{
    return [
        'id' => (int) $resource->id,
        'published' => (bool) $resource->published,
        'created_at' => Carbon::parse($resource->created_at),
    ];
}
```

**Comment by kevdotbadger** [comment]
This is semi done in https://github.com/ezdeliveryco/snorlax/pull/4

This PR allows you to define an ->after() method, this method could be used to case the response to an object.
