### ISSUE TITLE
Better cache layer

### ISSUE THREAD

**Issue by pedrommone** [ezdeliveryco/snorlax#2]
By the example, the current cache layer is not working.

**Comment by DennyLoko** [comment]
I want to work on this issue

**Comment by pedrommone** [comment]
Go ahead mate! :)

**Comment by pedrommone** [comment]
I was thinking about some cache strategies and I think we should handle cache invalidation here, I'll explain why. 

Imagine the resource `GET /stores`, in the perfect world, must be cached.
- When someone call `POST /stores` the resource should be invalidated.
- When someone call `PUT /stores/1` or `DELETE /stores/1` the resource `GET /stores/1` and `GET /stores` should be invalidated.
