### ISSUE TITLE
Increase code coverage up to 100%!

### ISSUE THREAD

**Issue by pedrommone** [ezdeliveryco/snorlax#31]
If we check [this link](https://codecov.io/gh/ezdeliveryco/snorlax/src/d8d1b7cdd0347bfeccdc94607652d4887d54be2a/src/RestClient.php#L117) we can see that there is only a failure point :)

**Comment by nitishkd** [comment]
I have minimal exp in php but from what i understood, possible fix can be : $this->middleware = new CacheMiddleware(); 
Am i correct?

**Comment by pedrommone** [comment]
@nitishkd: @jmauerhan has already sent this MR, I suggest you to take a look of how she did that :)

**Comment by pedrochaves** [comment]
Closed on #39 :)
