### ISSUE TITLE
Update PHPUnit to latest version

### ISSUE THREAD

**Issue by pedrochaves** [ezdeliveryco/snorlax#40]
We are still using PHPUnit 4.0 and the current version is already 5.5. We need to do two things while it's still "easy" to do:

- [ ] Update PHPUnit to version 5.5
- [ ] Switch `Mockery` for `Prophecy`, that comes out of the box with the next version of PHPUnit

**Comment by lucasmezencio** [comment]
Is it 'switch from mockery to prophecy' impeditive?

**Comment by pedrochaves** [comment]
Nope, this issue can be made in two steps.

**Comment by ocesaroliveira** [comment]
@pedrochaves I can do this! 👍
