### ISSUE TITLE
Action parameter order not being respected

### ISSUE THREAD

**Issue by lucasmezencio** [ezdeliveryco/snorlax#46]
When defining some `Resource` actions, the parameters in URI are not respected as regards the sorting:
```php
// ...
            'get' => [
                'method' => 'GET',
                'path'   => '/{1}?user_id={0}',
            ],
// ...
```

When the parameters are replaced, the index order are always by 0, 1, and then.
So, if we pass:
```php
$userId = 2;
$orderId = 10;
$resource->get($userId, $orderId);
```

The expected result is:
`/10?user_id=2`
But we get:
`/2?user_id=10`

**Comment by jmauerhan** [comment]
I'd be happy to take a look at this.
