### ISSUE TITLE
Accessing the RestClient instance from a Resource

### ISSUE THREAD

**Issue by kevdotbadger** [ezdeliveryco/snorlax#5]
Hello, another quick question! 

I'd making 2 calls to 
`$product = $client->Product->get(3166647429);` and 
`$product->metafields = $client->ProductMetafield->all($product->id);`

If the resource had access to the original RestClient, I could do this in 1 call and merge together before returning it. I'm planning to use DI, so I could reinstanciate the RestClient, but it would be handy if we could have access to the RestClient.

**Comment by lucasmezencio** [comment]
Hi @kevdotbadger!

It is a great idea! Actually, we do not feel the need, because we work differently here.

Do you have any thoughts about this? 
How do you think this can be done?

Can you open a PR with this feature?

**Comment by kevdotbadger** [comment]
I did a lil hack and basically when you create the client, I put `$this->client->restClient = $this;` 

Then from the resource you can access the RestClient with `$this->client->restClient` which'll refer to the SnorlaxRest instance. Then inside a resources `parse()` method you can do additional Rest calls.

I also renamed `$client` to `$httpClient` as it's confusing having a `GuzzleClient` and a `RestClient` floating around.

Any idea if this method will screw up when defining your own client?

**Comment by pedrommone** [comment]
Can you open a issue describing the expected result? We can discuss it and find a better way to reach that result.

**Comment by pedrochaves** [comment]
I am not sure about this is the best approach for the code design. Snorlax is meant to be as simple as possible and making another request inside the `parse()` params seems like difficult to debug and almost the same thing as making it after the initial one.

Maybe we can define composite requests on the configuration. This way the client wouldn't have to be exposed to the resources and it would be more explicit than making more than one request on `parse()`. What do you think?

**Comment by diegoholiveira** [comment]
hey @kevdotbadger one question: instead of change the client, why not create a new endpoint in your API that brings those results together in a single request?

**Comment by pedrommone** [comment]
@diegoholiveira probably hes trying to 'map' those relationships. We should draft something like it and call `eadge resources` and draft it! :)

**Comment by diegoholiveira** [comment]
> @diegoholiveira probably hes trying to 'map' those relationships. We should draft something like it and call eadge resources and draft it! :)

I understand that, but I'm suggesting that he could make the API give the entity with the relationship that he needs in one specific API endpoint, so, it will be faster than make 2 requests before parse/populate it's entities.

**Comment by pedrommone** [comment]
@diegoholiveira maybe we could use something like [this](http://stackoverflow.com/questions/22331676/the-restful-way-to-include-or-not-include-children-of-a-resource). What do you think?

**Comment by diegoholiveira** [comment]
> @diegoholiveira maybe we could use something like this. What do you think?

If you're talking about this: http://stackoverflow.com/a/22331993
Then yes. I like this way of thinking about endpoints.

**Comment by pedrommone** [comment]
@diegoholiveira that's what I thought :). I've open an issue #41 for this featura.

**Comment by diegoholiveira** [comment]
@pedrommone can you close this please?

**Comment by hernandev** [comment]
**`Singleton`** the Client :)

![](https://s3.minijuegosgratis.com/media/video-collection-img/video-collection-trollface-thumb.jpg)
