### ISSUE TITLE
Remove Collection dependency

### ISSUE THREAD

**Issue by pedrommone** [ezdeliveryco/snorlax#62]
Today, we're using `Illuminate\Support\Collection` at some specific points. I think it should be removed and replaced with vanilla PHP.

```
        if ($this->cache->has($resource)) {
            return $this->cache->get($resource);
        }
```

As we can see, it can be easily replaced.

**Comment by hernandev** [comment]
Don't!

**Comment by pedrommone** [comment]
@hernandev why? We're using it *TWO times* only, there's no need for such overhead.

**Comment by jgrossi** [comment]
😎
